apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fast-api-app.fullname" . }}
  labels:
    {{- include "fast-api-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fast-api-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fast-api-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http